services:
  postgres:
    image: postgres:latest
    container_name: django_vite_tailwind_starter
    ports:
      - "65432:5432"
    environment:
      POSTGRES_DB: postgres_name
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: